### ISSUE TITLE
training multi images per batch

### ISSUE THREAD

**Issue by andy4120** [ZrrSkywalker/Personalize-SAM#15]
hi ，there
    I wonder whether we can add mutli images every batch size to finetune

**Comment by ZrrSkywalker** [comment]
Hi thanks for your interest and this valuable suggestion!
As our work is now focusing on one-shot learning, there is only one training image. We will further release the few-shot PerSAM with multiple images every batch to fine-tune. Thanks!

**Comment by andy4120** [comment]
ok，thx
