### ISSUE TITLE
persam_f.py: error: argument --lr: invalid int value: '0.01'

### ISSUE THREAD

**Issue by xyqlx** [ZrrSkywalker/Personalize-SAM#19]
https://github.com/ZrrSkywalker/Personalize-SAM/blob/c1effd8d8b2dc166dcf8e6927602123dd0387c96/persam_f.py#L27

should be changed to

```python
parser.add_argument('--lr', type=float, default=1e-3) 
```

**Comment by ZrrSkywalker** [comment]
Thanks very much for pointing out! We have fixed this bug.
