### ISSUE TITLE
evaluation code for VOS

### ISSUE THREAD

**Issue by MaureenZOU** [ZrrSkywalker/Personalize-SAM#2]
Hi Authors, thanks so much for your interesting work! It looks pretty cool : )

It would be really appreciated if you could like to share the evaluation code for VOS! And we just release the Focal-L model, feel free to get new numbers on Table.1 for SEEM : )

Best,
Xueyan

**Comment by jiangzhengkai** [comment]
@MaureenZOU Thanks for your kind suggestion, we will add SEEM results of the Focal-L model

**Comment by MaureenZOU** [comment]
Also It would be really appreciated if you could like to share the evaluation code for VOS 🌲

**Comment by ZrrSkywalker** [comment]
@MaureenZOU  Sure, we will soon release the VOS code :). Also, thanks for your wonderful and insightful work SEEM.

**Comment by MaureenZOU** [comment]
Thanks a lot for your great work and prompt response too!

**Comment by jiangzhengkai** [comment]
![image](https://user-images.githubusercontent.com/19780166/236388056-6340d82d-aa28-4beb-ad71-04ddc8da0df3.png)
@MaureenZOU We have evaluated the SEEM-Focal-L model, and the result will be added to our updated version.

**Comment by MaureenZOU** [comment]
Many appreciation for your response! That gives good understanding for us of how SEEM performs in personalized segmentation.
